#!/usr/bin/env python
"""§38B: Object Permanence audit.

For each object: look at it -> turn out of FOV (15 chunks) -> wait H chunks ->
turn back to the original pose. Compare the object's patch in frame 0 with the
return frame, in five dimensions:

    Existence   best DINO similarity in a search window above a threshold
    Identity    DINO similarity at the best match
    Pose        displacement of the best match (px)
    Attributes  LPIPS of the best-matched patch
    Relations   consistency of the pairwise offsets between objects

  LINGBOT_FP8=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
  python object_permanence.py --scenes 04,01 --seeds 42
"""
import argparse
import gc
import hashlib
import json
import math
import os
import shutil
import sys

import cv2
import numpy as np
import torch
from PIL import Image

import wan
from wan.configs import WAN_CONFIGS
from cam_controller import CameraController
from wan.utils.cam_utils import get_Ks_transformed, interpolate_camera_poses, \
    compute_relative_poses, get_plucker_embeddings
from einops import rearrange

sys.path.insert(0, os.path.expanduser("~/ai/taehv"))
from taehv import TAEHV  # noqa: E402

PROMPT = "A first-person view of a natural landscape with smooth camera motion."
HORIZONS = [4, 6, 8, 10, 12]     # TOTAL out-of-FOV chunks (turn out + turn back)

# peripheral objects only: they sit at ~27 deg off-axis, so a 2-6 chunk yaw
# (12-36 deg) is enough to take them out of the ~29 deg half-FOV.
OBJECTS = {
    "04": {
        "right_wall":  (0.82, 0.58, 1.00, 1.00),
        "left_wall":   (0.00, 0.58, 0.18, 1.00),
        "watchtower":  (0.68, 0.42, 0.88, 0.72),
        "trees_right": (0.86, 0.15, 1.00, 0.55),
        "hill_left":   (0.00, 0.08, 0.16, 0.42),
    },
    "01": {
        "far_right_stone": (0.84, 0.32, 1.00, 0.74),
        "left_trilithon":  (0.02, 0.30, 0.22, 0.70),
        "right_stone":     (0.58, 0.24, 0.74, 0.66),
        "fg_left_grass":   (0.00, 0.72, 0.18, 0.95),
        "center_trilithon": (0.32, 0.25, 0.55, 0.65),
    },
}


def build_traj(scene, total_out):
    """Reference and revisit are BOTH at the start pose, generated by the model.

    Layout (chunks):
        2 chunks at start pose   <- reference taken from chunk 1
        T chunks turning out     (T = total_out // 2)
        T chunks turning back    (exact mirror)
        2 chunks at start pose   <- revisit taken from the last chunk

    So the out-of-FOV duration is exactly `total_out` chunks
    (= total_out * 0.25 s of video time, since 1 chunk = 4 frames @ 16 fps).
    """
    T = max(1, total_out // 2)
    p = np.load(f"examples/{scene}/poses.npy")
    ctl = CameraController(p[0, :3, :3], p[0, :3, 3])
    ctl.cfg.yaw_rate_max, ctl.cfg.pitch_rate_max, ctl.cfg.v_max = 6.0, 2.0, 1.0
    start = ctl.pose.copy()
    out = []
    ctl.set_input(yaw=1.0)
    for _ in range(T * 4):
        ctl.step(dt=0.25)
        out.append(ctl.pose.copy())
    fr = [start] * 8 + out + out[::-1] + [start] * 8
    traj = np.stack(fr)
    n = (len(traj) - 1) // 4 * 4 + 1
    return traj[:n], 2, total_out   # ref chunk index, out-of-FOV chunks


def patch(img, bb):
    H, W = img.shape[:2]
    x0, y0, x1, y1 = bb
    return img[int(y0 * H):int(y1 * H), int(x0 * W):int(x1 * W)]


def best_match(feat_fn, ref_patch, ret_img, bb, search=0.06, steps=13):
    """Slide the reference patch over a LOCAL window around the expected location.

    A fixed crop would fold the pose error into identity loss; the best match
    separates 'the thing changed' from 'the thing moved a few pixels'.
    """
    H, W = ret_img.shape[:2]
    x0, y0, x1, y1 = bb
    pw, ph = x1 - x0, y1 - y0
    sw, sh = int(pw * W), int(ph * H)
    best = (-1.0, None, None)
    fr = feat_fn(ref_patch)
    for dy in np.linspace(-search, search, steps):
        for dx in np.linspace(-search, search, steps):
            bx = int((x0 + dx) * W); by = int((y0 + dy) * H)
            if bx < 0 or by < 0 or bx + sw > W or by + sh > H:
                continue
            cand = ret_img[by:by + sh, bx:bx + sw]
            if cand.size == 0:
                continue
            sim = float((fr * feat_fn(cand)).sum())
            if sim > best[0]:
                best = (sim, (bx, by), cand)
    return best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", default="i2v-1.3B")
    ap.add_argument("--ckpt_dir", default=os.path.expanduser("~/ai/models/lingbot-world-v2-1.3b-causal-fast"))
    ap.add_argument("--assets_dir", default=os.path.expanduser("~/ai/models/lingbot-shared-assets"))
    ap.add_argument("--scenes", default="04,01")
    ap.add_argument("--seeds", default="42,123,7")
    ap.add_argument("--horizons", default="4,6,8,10,12")
    ap.add_argument("--area", default="512x320")
    ap.add_argument("--tae_pth", default=os.path.expanduser("~/ai/taehv/taew2_1.pth"))
    ap.add_argument("--out_dir", default="output/objperm")
    args = ap.parse_args()

    W, H = (int(x) for x in args.area.lower().split("x"))
    cfg = WAN_CONFIGS[args.task]
    os.makedirs(args.out_dir, exist_ok=True)
    horizons = [int(x) for x in args.horizons.split(",")]
    scenes = args.scenes.split(",")
    seeds = [int(x) for x in args.seeds.split(",")]

    pipe = wan.WanI2VCausal(
        config=cfg, checkpoint_dir=args.ckpt_dir, device_id=0, rank=0,
        t5_fsdp=False, dit_fsdp=False, use_sp=False, t5_cpu=True,
        convert_model_dtype=False, local_attn_size=6, sink_size=1,
        infer_mode="causal_fast", assets_dir=args.assets_dir)
    dev, pdt, dtype = pipe.device, pipe.param_dtype, pipe.pipe_dtype
    tae = TAEHV(checkpoint_path=args.tae_pth).to(dev).eval()
    print("[op] pipe + TAE built", flush=True)
    key = hashlib.sha256(PROMPT.encode()).hexdigest()
    ctx = pipe.text_encoder([PROMPT], torch.device("cpu"))
    pipe._t5_cache[key] = [t.to(pipe.device) for t in ctx]
    pipe.text_encoder = None
    gc.collect(); torch.cuda.empty_cache()
    vae_stride, patch_sz = pipe.vae_stride, pipe.patch_size
    ma = pipe.model.config
    lh = ma.num_heads // pipe.sp_size; hd = ma.dim // ma.num_heads
    from eval_two_layer import load_models, dino_feat, lpips_d
    load_models()

    rows = []
    for scene in scenes:
        for sd in seeds:
            for hz in horizons:
                traj, ref_chunk, out_chunks = build_traj(scene, hz)
                frames_n = len(traj)
                d = f"examples/op_{scene}_H{hz}"
                os.makedirs(d, exist_ok=True)
                np.save(f"{d}/poses.npy", traj)
                shutil.copy(f"examples/{scene}/intrinsics.npy", f"{d}/intrinsics.npy")
                shutil.copy(f"examples/{scene}/image.jpg", f"{d}/image.jpg")
                img_pil = Image.open(f"{d}/image.jpg").convert("RGB")
                import torchvision.transforms.functional as TF
                img = TF.to_tensor(img_pil).sub_(0.5).div_(0.5).to(dev)
                h, w = img.shape[1:]
                aspect = h / w
                lat_h = round(math.sqrt(W * H * aspect) // vae_stride[1] // patch_sz[1] * patch_sz[1])
                lat_w = round(math.sqrt(W * H / aspect) // vae_stride[2] // patch_sz[2] * patch_sz[2])
                h = lat_h * vae_stride[1]; w = lat_w * vae_stride[2]
                fsl = (lat_h * lat_w) // (patch_sz[1] * patch_sz[2])
                max_seq_len = int(math.ceil(fsl / pipe.sp_size)) * pipe.sp_size
                kv_size = fsl * 6
                n_lat = (frames_n - 1) // 4 + 1
                pipe.prewarm(img_pil, max_area=W * H, frame_num=frames_n, chunk_size=1)
                Ks = get_Ks_transformed(
                    torch.from_numpy(np.load(f"{d}/intrinsics.npy")).float(),
                    480, 832, h, w, h, w)[0].to(dev)
                y = pipe.vae.encode([torch.concat([
                    torch.nn.functional.interpolate(img[None].cpu(), size=(h, w),
                                                    mode='bicubic').transpose(0, 1),
                    torch.zeros(3, frames_n - 1, h, w)], dim=1).to(dev)])[0]
                msk = torch.ones(1, frames_n, lat_h, lat_w, device=dev)
                msk[:, 1:] = 0
                msk = torch.concat([torch.repeat_interleave(msk[:, 0:1], repeats=4, dim=1),
                                    msk[:, 1:]], dim=1)
                msk = msk.view(1, msk.shape[1] // 4, 4, lat_h, lat_w).transpose(1, 2)[0]
                y = torch.concat([msk, y])
                self_kv = pipe._initialize_self_kv_cache(
                    num_layers=ma.num_layers, shape=[1, kv_size, lh, hd],
                    dtype=dtype, device=dev)
                cross_kv = pipe._initialize_crossattn_cache(
                    num_layers=ma.num_layers, shape=[1, 512, ma.num_heads, hd],
                    dtype=dtype, device=dev)
                pipe._cross_attn_initialized = False
                timesteps = pipe.scheduler.timesteps[[0, 250, 750]]
                g = torch.Generator(device=dev); g.manual_seed(sd)
                c2w = interpolate_camera_poses(
                    np.linspace(0, frames_n - 1, frames_n),
                    torch.from_numpy(traj[:, :3, :3]).float(),
                    torch.from_numpy(traj[:, :3, 3]).float(),
                    np.linspace(0, frames_n - 1, n_lat)).to(dev)
                rel_all = compute_relative_poses(c2w, framewise=True)
                outs = []
                for cid in range(n_lat):
                    cur = torch.randn(16, 1, lat_h, lat_w, generator=g, device=dev)
                    p = get_plucker_embeddings(rel_all[cid:cid + 1], Ks[None], h, w)
                    p = rearrange(p, 'f (h c1) (w c2) c -> (f h w) (c c1 c2)',
                                  c1=int(h // lat_h), c2=int(w // lat_w))[None]
                    plk = rearrange(p, 'b (f h w) c -> b c f h w', f=1,
                                    h=lat_h, w=lat_w).to(pdt)
                    kw = {"context": [pipe._t5_cache[key][0]], "seq_len": max_seq_len,
                          "y": [y.split(1, dim=1)[min(cid, frames_n // 4 - 1)]],
                          "dit_cond_dict": {"c2ws_plucker_emb": plk.chunk(1, dim=0)},
                          "kv_cache": self_kv, "crossattn_cache": cross_kv,
                          "current_start": cid * fsl,
                          "max_attention_size": kv_size, "frame_seqlen": fsl}
                    for ti in range(len(timesteps)):
                        with torch.amp.autocast("cuda", dtype=pdt), torch.no_grad():
                            npred = pipe.model(
                                x=[cur.to(dev)], t=torch.stack([timesteps[ti]]).to(dev),
                                cross_attn_first_call=not pipe._cross_attn_initialized,
                                **kw)[0]
                            pipe._cross_attn_initialized = True
                            x0 = pipe._convert_flow_pred_to_x0(
                                flow_pred=npred, xt=cur, timestep=timesteps[ti],
                                scheduler=pipe.scheduler)
                            if ti < len(timesteps) - 1:
                                cur = pipe.scheduler.add_noise(
                                    x0, torch.randn(x0.shape, generator=g,
                                                    device=x0.device, dtype=x0.dtype),
                                    timesteps[ti + 1])
                    with torch.amp.autocast("cuda", dtype=pdt), torch.no_grad():
                        pipe.model(x=[x0], t=torch.stack([timesteps[-1] * 0.0]).to(dev),
                                   cross_attn_first_call=False, **kw)
                    with torch.no_grad():
                        fr = tae.decode_video(x0.permute(1, 0, 2, 3).unsqueeze(0),
                                              parallel=False, show_progress_bar=False)
                    outs.append((fr[0][0].permute(1, 2, 0).float().cpu().numpy()
                                 * 255.0).clip(0, 255).astype(np.uint8))
                    if cid % 15 == 0:
                        print(f"[op] {scene}/H{hz}/s{sd} chunk {cid}/{n_lat}", flush=True)
                # generated-reference vs generated-revisit (no input photo involved)
                f0 = outs[min(ref_chunk, len(outs) - 1)]
                fret = outs[-1]
                objs = OBJECTS[scene]
                whole = float((dino_feat(f0) * dino_feat(fret)).sum())
                print(f"[op] {scene}/H{hz}/s{sd} out={out_chunks}ch "
                      f"({out_chunks*0.25:.2f}s) WHOLE-FRAME DINO = {whole:.3f}",
                      flush=True)
                centers0, centers1 = {}, {}
                for name, bb in objs.items():
                    rp = patch(f0, bb)
                    sim, pos, cand = best_match(dino_feat, rp, fret, bb)
                    Hh, Ww = fret.shape[:2]
                    exp = (int((bb[0] + bb[2]) / 2 * Ww), int((bb[1] + bb[3]) / 2 * Hh))
                    if pos is not None:
                        disp = float(np.hypot(pos[0] - int(bb[0] * Ww),
                                              pos[1] - int(bb[1] * Hh)))
                        if cand.shape[:2] != rp.shape[:2]:
                            cand = cv2.resize(cand, (rp.shape[1], rp.shape[0]))
                        attrs = lpips_d(rp, cand)
                        centers0[name] = (int(bb[0] * Ww), int(bb[1] * Hh))
                        centers1[name] = (int(pos[0]), int(pos[1]))
                    else:
                        disp, attrs = float("nan"), float("nan")
                    rows.append(dict(scene=scene, seed=sd, H=hz, obj=name,
                                     existence=int(sim > 0.5), identity=sim,
                                     pose_disp=disp, attrs_lpips=attrs))
                    print(f"[op] {scene}/H{hz}/s{sd} {name:18s} DINO={sim:.3f} "
                          f"disp={disp:.1f}px LPIPS={attrs:.3f}", flush=True)
                # relations: pairwise offset consistency
                if len(centers0) >= 2:
                    ks = list(centers0.keys())
                    devs = []
                    for i in range(len(ks)):
                        for j in range(i + 1, len(ks)):
                            d0 = np.array(centers0[ks[i]]) - np.array(centers0[ks[j]])
                            d1 = np.array(centers1[ks[i]]) - np.array(centers1[ks[j]])
                            devs.append(float(np.linalg.norm(d0 - d1)))
                    rows.append(dict(scene=scene, seed=sd, H=hz, obj="__relations__",
                                     existence=1, identity=float("nan"),
                                     pose_disp=float(np.mean(devs)),
                                     attrs_lpips=float("nan")))
                del y, self_kv, cross_kv, outs
                gc.collect(); torch.cuda.empty_cache()

    print("\n[op] ===== object permanence summary =====")
    print(f"{'scene':6s} {'H':>3s} {'existence':>10s} {'identity':>9s} "
          f"{'pose_disp':>10s} {'attrs_lpips':>12s} {'relations':>10s}")
    for scene in scenes:
        for hz in horizons:
            sub = [r for r in rows if r["scene"] == scene and r["H"] == hz
                   and r["obj"] != "__relations__"]
            rel = [r for r in rows if r["scene"] == scene and r["H"] == hz
                   and r["obj"] == "__relations__"]
            if not sub:
                continue
            print(f"{scene:6s} {hz:3d} "
                  f"{np.mean([r['existence'] for r in sub]):10.2f} "
                  f"{np.nanmean([r['identity'] for r in sub]):9.3f} "
                  f"{np.nanmean([r['pose_disp'] for r in sub]):10.1f} "
                  f"{np.nanmean([r['attrs_lpips'] for r in sub]):12.3f} "
                  f"{(np.mean([r['pose_disp'] for r in rel]) if rel else float('nan')):10.1f}")
    json.dump(rows, open(f"{args.out_dir}/objperm.json", "w"), indent=1)


if __name__ == "__main__":
    main()
